### ISSUE TITLE
Load Layer - CAPAD 2016

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#111] opened 2019-07-15 22:51 UTC
# CAPAD 2016 Terrestrial

https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B4448CACD-9DA8-43D1-A48F-48149FD5FCFD%7D

- [x] Download shapefile for CAPAD 2016
- [x] Verify integrity of shapefile using local analysis and identify the label and class fields to use for spatial fields
- [x] Upload shapefile to `nectar-spatial-staging` and create layer https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10944
- [x] Create label field (`NAME`, has 10498 unique values out of 11181 polygons) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/field/cl10944
- [x] Create class field (`TYPE`, has 62 unique values out of 11181 polygons) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/field/cl110944
- [x] Copy to `aws-spatial-prod`
- [x] Copy to `ala-dylan`
- [x] Check that sampling/intersection is working
- [x] Enable layer and fields on `aws-spatial-prod`
- [x] Wait for resampling/reprocessing/reindexing (Runs weekly automatically on Tuesday through to Wednesday)
- [ ] Update any previous CAPAD references in biocache or regions facet lists to reference `CAPAD 2016 Terrestrial`

# CAPAD 2016 Marine

https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7BAF4EE98E-7F09-4172-B95E-067AB8FA10FC%7D

- [x] Download shapefile for CAPAD 2016 Marine
- [x] Verify integrity of shapefile using local analysis and identify the label and class fields to use for spatial fields
- [x] Upload shapefile to `nectar-spatial-staging` and create layer https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10945
- [x] Create label field (`NAME`, has 365 unique values out of 3347 polygons) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/field/cl10945
- [x] Create class field (`TYPE`, has 26 unique values out of 3347 polygons) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/field/cl110945
- [x] Copy to `aws-spatial-prod`
- [x] Copy to `ala-dylan`
- [x] Check that sampling/intersection is working
- [x] Enable layer and fields on `aws-spatial-prod`
- [x] Wait for resampling/reprocessing/reindexing (Runs weekly automatically on Tuesday through to Wednesday)
- [ ] Update any previous CAPAD Marine references in biocache or regions facet lists to reference `CAPAD 2016 Marine`

The full set of steps (some of the steps above are condensed versions of what is fully required) for layer loading is on the wiki at:

https://wiki.ala.org.au/wiki/Spatial-layer-loading

**Comment by Tasilee** [comment] 2019-07-15 22:55
Does this update cover the IEK areas? If so, can we remove one or more of #61, #71, #72?

**Comment by ansell** [comment] 2019-07-15 23:14
I am not familiar with CAPAD. There is a reference to Indigenous Protected Areas so #61 may have its content inside of CAPAD. However, I can't see references to the National Native Title Tribunal or RATSIB so the other two are possibly still required for the IEK project.

**Comment by Tasilee** [comment] 2019-07-15 23:17
Thanks @ansell. I am checking our existing layers now and note that ACT TAMS is in CAPAD for starters. I would hope the CAPAD metadata would include the classes covered.

**Comment by Tasilee** [comment] 2019-07-15 23:29
I reckon CAPAD (marine) also covers our layer "Australia's network of Marine Parks" (10912)

**Comment by ansell** [comment] 2019-07-15 23:43
The replacement for 10912 is tracked in https://github.com/AtlasOfLivingAustralia/layers-service/issues/110

**Comment by ansell** [comment] 2019-07-15 23:52
We updated `Australia's network of Marine Parks` at DoEE request within the last 12 months, and they want us to reload again (since about 3 weeks ago) to fix a correction. Based on that situation, it won't be deprecated by CAPAD 2016 which will have out of date boundaries/labels compared to what we currently have loaded and the correction they have already asked me to fix, but it may be deprecated by a future CAPAD version.

**Comment by ansell** [comment] 2019-07-16 00:07
The shapefiles I downloaded look intact based on their expected domains:

Marine: ![CAPAD_2016_marine](https://user-images.githubusercontent.com/82365/61256779-5e9e6680-a7b1-11e9-8874-0b5a1db72a74.png)

Terrestrial: ![CAPAD_2016_terrestrial](https://user-images.githubusercontent.com/82365/61256780-5e9e6680-a7b1-11e9-950a-342722db46e3.png)

**Comment by Tasilee** [comment] 2019-07-16 00:47
Re #110, ok. I guess we live with some overlaps.

**Comment by ansell** [comment] 2019-07-16 01:35
@Tasilee The 2 layers (4 fields) are available on https://nectar-spatial-staging.ala.org.au/ Can you test them out to see if they are what you expected?

**Comment by Tasilee** [comment] 2019-07-16 02:49
Wow, quick! 

It looks to me that Terrestrial = Terrestrial (classes) and Marine = Marine (classes)

i.e. the 2 layers with reserve names are not there

**Comment by ansell** [comment] 2019-07-16 03:01
There are two layers, each with two fields (4 fields in total). Just double checking myself, but they look as intended:

* cl10945 CAPAD 2016 Marine, looks like it is based on the `NAME` field as intended with the expected 365 unique values
* cl110945 CAPAD 2016 Marine (Classes), looks like it is based on the `TYPE` field as intended with the expected 26 unique values
* cl10944 CAPAD 2016 Terrestrial, looks like it is based on the `NAME` field as intended with the expected 10498 unique values
* cl110944 CAPAD 2016 Terrestrial (Classes), looks like it is based on the `TYPE` field as intended with the expected 62 unique values

**Comment by Tasilee** [comment] 2019-07-16 04:37
That looks correct, but we aren't getting the correct legends for NAME, e.g., Marine
![Capture](https://user-images.githubusercontent.com/6656350/61266435-36296300-a7d7-11e9-86ff-acdbe5fc2916.jpg)

**Comment by ansell** [comment] 2019-07-16 05:06
I am not sure what the issue is with that legend. Can you clarify which values I need to look into?

**Comment by ansell** [comment] 2019-07-16 05:23
Sorry, I have been looking at this for too long today and missed the obvious error. The issue seems to be that the `CAPAD 2016 Marine (Classes)` items are showing up in the legend for `CAPAD 2016 Marine`. I double-checked, and that isn't how it is configured in the background (the source and label are both `NAME`) so that would be a spatial-portal or spatial-service bug, and won't block moving this through the pipeline.

**Comment by ansell** [comment] 2019-07-16 05:29
Opened an issue on spatial-hub to track fixing it, but I won't delay finishing this layer load on getting it fixed:

https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/237

**Closed** 2019-07-30 04:27 UTC
Labels: IEK, Spatial Layer, priority-high

**Comment by ansell** [comment] 2019-07-30 04:42
The final steps of updating the facets that biocache and regions use for this are being followed up separately in bulk along with PSMA.
